baseurl = "https://www.matteobianchi.eu" # Controls base URL sitewide
languageCode = "en-US" # Controls site language
title = "Matteo Bianchi personal site and blog" # Homepage title and page title suffix
paginate = 11 # Number of posts to show before paginating

# Controls default theme and theme components
theme = [
  "toxic-swamp",
  "fractal-forest",
  "after-dark"
]

disableLiveReload = false # Optional, set true to disable live reload
enableRobotsTXT = true # Suggested, enable robots.txt file

pygmentsCodefences = true # Suggested, highlight fenced code blocks
pygmentsUseClasses = true # Required for custom syntax highlighting

sectionPagesMenu = "main" # Enable menu system for lazy bloggers
footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link

[params]
  description = "" # Suggested, controls default description meta
  author = "" # Optional, controls author name display on posts
  hide_author = false # Optional, set true to hide author name on posts
  has_cookies = false # Optional, set true to disable cookie disclaimer
  related_content_limit = 5

  disable_csp = false # Optional, set true to disable content security policy
  images = [
    "https://source.unsplash.com/collection/983219/2000x1322"
  ] # Suggested, controls default Open Graph images

[params.layout.menu.main]
  hidden = false # Optional, set false or remove to show section menu

[params.modules.fractal_forest]
  enabled = true # Optional, set false to disable module
  decoders = ["bpgdec8a"] # Optional, 8-bit javascript decoder with animation

#for menu showing

[[params.layout.home.section]]
  type = "post"
  limit = 3


[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Posts"
  weight = 2
  identifier = "post"
  url = "/posts/"

[[menu.main]]
  name = "GreatJsgame"
  weight = 10
  identifier = "game"
  url = "/game/"

[[menu.main]]
  name = "Appunti universitari"
  weight = 14
  identifier = "appunti"
  url = "/appunti/"



[outputs]
  home = ["HTML", "RSS", "JSON"]

[params.modules.toxic_swamp]
  enabled = true # Optional, set false to disable module
  address = "44ZFEBS92j2T3LyJ5mMJmqA91wtByt5NBitXA9H97u1RY2x44crTtr52is3uyGt9dm3PN9nXfpzGHDB9mUtLyQseVrryYk4"



